version: "3"
services:
  es:
    image: elasticsearch:5.6.8
    ports:
      - "9200:9200"
    volumes:
      - "./es/data:/usr/share/elasticsearch/data"
      - "./es/conf/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml"